import os


DB_PATH = "dns_sentinel.db"

ENTROPY_THRESHOLD = 3.5

NXDOMAIN_BURST_THRESHOLD = 5
NXDOMAIN_BURST_WINDOW = 60

DNS_TUNNELING_LENGTH_THRESHOLD = 25
DNS_TUNNELING_ENTROPY_THRESHOLD = 3.8

WATER_TORTURE_THRESHOLD = 3
WATER_TORTURE_WINDOW = 60
WATER_TORTURE_ENTROPY_RATIO = 0.3
WATER_TORTURE_IP_THRESHOLD = 1
WATER_TORTURE_SUBDOMAIN_ENTROPY_THRESHOLD = 2.3
WATER_TORTURE_NXDOMAIN_RATIO = 0.70
WATER_TORTURE_QPS_THRESHOLD = 3

SLOW_WATER_TORTURE_WINDOW = 1800      # 30 minutes
SLOW_WATER_TORTURE_THRESHOLD = 80
SLOW_WATER_TORTURE_NXDOMAIN_RATIO = 0.60
SLOW_WATER_TORTURE_ENTROPY_RATIO = 0.50

WATER_TORTURE_SCORE_THRESHOLD = 80

AUTO_BLOCK_SCORE_THRESHOLD = 100
BLOCKLIST_FILE = "logs/blocked_ips.txt"

LOG_FILE = "logs/detections.log"
EMAIL_ENABLED = True

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

EMAIL_SENDER = "salmayounes648@gmail.com"
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD", "")

EMAIL_RECEIVER = ""


INTERNAL_NETWORKS = [
    "127.0.0.0/8",
        "10.0.0.0/8",
            "172.16.0.0/12",
                "192.168.0.0/16"
                ]
                IP_SCORE_THRESHOLD = 10

                PSEUDO_RANDOM_MIN_LENGTH = 10

                PSEUDO_RANDOM_MAX_VOWEL_RATIO = 0.25

                PSEUDO_RANDOM_MIN_UNIQUE_BIGRAMS = 8

                