DB_PATH = "dns_sentinel.db"

ENTROPY_THRESHOLD = 3.5

NXDOMAIN_BURST_THRESHOLD = 5
NXDOMAIN_BURST_WINDOW = 60

DNS_TUNNELING_LENGTH_THRESHOLD = 25
DNS_TUNNELING_ENTROPY_THRESHOLD = 3.8

WATER_TORTURE_THRESHOLD = 3
WATER_TORTURE_WINDOW = 60
WATER_TORTURE_ENTROPY_RATIO = 0.3
WATER_TORTURE_IP_THRESHOLD = 1
WATER_TORTURE_SUBDOMAIN_ENTROPY_THRESHOLD = 2.3

AUTO_BLOCK_SCORE_THRESHOLD = 100
BLOCKLIST_FILE = "logs/blocked_ips.txt"

LOG_FILE = "logs/detections.log"